cc_test(
    name = "coded_stream_test",
    size = "small",
    srcs = ["coded_stream_test.cc"],
    deps = [
        "//runtime/decaproto/stream:stream",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "reflection_test",
    size = "small",
    srcs = ["reflection_test.cc"],
    deps = [
        "//runtime/decaproto:decaproto",
        "@com_google_googletest//:gtest_main",
    ],
)
