cc_library(
    name = "stream",
    srcs = [
        "coded_stream.cc",
    ],
    hdrs = [
        "coded_stream.h",
        "stl_stream_wrapper.h",
        "stream.h",
    ],
    includes = ["."],
    strip_include_prefix = "/runtime",
    visibility = ["//visibility:public"],
)
