cc_library(
    name = "decaproto",
    hdrs = [
        "descriptor.h",
        "message.h",
        "reflection.h",
    ],
    strip_include_prefix = "/runtime",
    visibility = ["//visibility:public"],
)
